services:
  redis:
    container_name: redis
    hostname: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf:ro
      - ./redis/users.acl:/etc/redis/users.acl:ro
    command: ["redis-server", "/etc/redis/redis.conf"]
